baseURL: "https://koukyosyumei.github.io/KoukyosyumeiResume2/" 
title: Hideaki Takahashi
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

menu:
    main:
        - name: Papers
          url: papers/
          weight: 1
            #- name: Courses
            #url: courses/
            #weight: 2
            #- name: Data
            #url: data/
            #weight: 3 
            #- name: Newsletter
            #url: https://pmichaillat.substack.com
            #weight: 4

params:
    description: "I am a first-year PhD student in the Computer Science department at Columbia University. I received a Bachelor of Arts and Science at the University of Tokyo in 2024, majoring in Informatics. My main interests lie at the intersection of AI, security, privacy, and system technologies."
    author: Hideaki Takahashi
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "Nov. 2023"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Hideaki Takahashi
          subtitle: "<u><a href='https://koukyosyumei.github.io/KoukyosyumeiResume/jp/'>日本語版はこちら</a></u><br/><br/>I am a first-year PhD student in Computer Science department at Columbia University, advised by <u><a href='https://www.cs.columbia.edu/~junfeng/'>Prof. Junfeng Yang</a></u>. I also work closely with <u><a href='https://www.cs.columbia.edu/~suman/'>Prof. Suman Jana</a></u>. My research interests revolve around AI, security, privacy, and systems. My current work focuses on Zero Knowledge Proofs.<br/><br/>I received a Bachelor of Arts and Science in Informatics from the University of Tokyo, where I was advised by <u><a href='http://www.metahack.org/'>Prof. Alex Fukunaga</a></u>, focusing on privacy-preserving AI planning. During my undergraduate studies, I spent a gap year as a research intern at Tsinghua University under the supervision of <u><a href='https://sites.google.com/site/yangliuveronica/home'>Prof. Yang Liu</a></u> and <u><a href='https://scholar.google.com/citations?user=BzJ_GboAAAAJ'>Prof. Jingjing Liu</a></u>, investigating security vulnerabilities in Federated Learning.<br/><br/>I am also passionate about open-source development. My project, AIJack, which aims to attack, defend, and debug machine learning models, has gained traction with over 300 stars on GitHub and has been widely used in research."
          imageUrl: "newface.jpg"
          imageWidth: 160
          imageHeight: 160
          imageTitle: Hideaki Takahashi
          buttons:
            - name: CV
              url: https://koukyosyumei.github.io/KoukyosyumeiResume/assets/CV.pdf
            - name: Semantic Scholar
              url: https://www.semanticscholar.org/author/Hideaki-Takahashi/2224016223
            - name: Google Scholar
              url: https://scholar.google.com/citations?user=RA3z3UEAAAAJ
            - name: GitHub
              url: https://github.com/Koukyosyumei
                #- name: Data
                #url: data/
                #- name: Newsletter
                #url: https://pmichaillat.substack.com
                #- name: Tags
                #url: tags/
                #- name: Archive
                #url: archive/
          educations:
            - title: "Columbia University"
              date: "Sep. 2024 ~ "
              description: "Ph.D. Student (Computer Science)"
            - title: "The University of Tokyo"
              date: "Apr. 2019 ~ Mar. 2024"
              description: "Bachelor of Arts and Science (Informatics)"
          publications:
            - title: "On the Transit Obfuscation Problem."
              venue: "AAMAS'24"
              url: https://arxiv.org/pdf/2402.07420.pdf
              authors: "<u>Hideaki Takahashi*</u>, Alex Fukunaga"
              publisher: "Proceedings of the International Conference on Autonomous Agents and Multi-Agent Systems"
              date: "2024"
            - title: "VFLAIR, A Research Library and Benchmark for Vertical Federated Learning."
              venue: "ICLR'24"
              url: https://arxiv.org/pdf/2310.09827.pdf
              authors: "Zou, Tianyuan, Zixuan Gu, Yuanqin He, <u>Hideaki Takahashi</u>, Yang Liu, Guangnan Ye and Ya-Qin Zhang"
              publisher: "Proceedings of the International Conference on Learning Representations"
              date: "2024"
            - title: "Breaching FedMD, Image Recovery via Paired-Logits Inversion Attack."
              venue: "CVPR'23"
              url: https://arxiv.org/pdf/2304.11436.pdf
              authors: "<u>Hideaki Takahashi*</u>, Jingjing Liu, and Yang Liu."
              publisher: "Proceedings of the IEEE/CVF Conference on Computer Vision and Pattern Recognition"
              date: "2023"
          preprints:
            - title: "Eliminating Label Leakage in Tree‑based Vertical Federated Learning. arXiv:2307.10318"
              url: https://arxiv.org/pdf/2307.10318.pdf
              authors: "<u>Hideaki Takahashi*</u>, Jingjing Liu, and Yang Liu"
              date: "2023"
            - title: "Difficulty of Detecting Overstated Dataset Size in Federated Learning. Technical Report of DPS, 10, Information Processing Society of Japan."
              url: http://id.nii.ac.jp/1001/00214220/
              authors: "<u>Hideaki Takahashi*</u>, Kohei Ichikawa, and Keichi Takahashi"
              date: "2021"
          softwares:
            - title: AIJack
              url: https://koukyosyumei.github.io/AIJack/
              badges:
                  - url: "https://badgen.net/github/stars/Koukyosyumei/AIjack?color=green"
                  - url: "https://badgen.net/github/forks/Koukyosyumei/AIjack"
              description: "Security risk simulator for machine learning (more than 300 stars on GitHub and used in 8 papers)"
            - title: rhoevm
              url: https://github.com/Koukyosyumei/rhoevm
              badges:
                  - url: "https://badgen.net/github/stars/Koukyosyumei/rhoevm?color=green"
              description: "Symbolic EVM execution engine written in Rust to find vulnerabilities within Ethereum smart contracts"
            - title: Gymbo
              url: https://github.com/Koukyosyumei/Gymbo
              badges:
                  - url: "https://badgen.net/github/stars/Koukyosyumei/Gymbo?color=green"                
              description: "Symbolic execution engine using gradient descent to solve path constraints"  
            - title: "My*"
              description: This series aims to implement various algorithms, compilers, and solvers from scratch.
              subprojects:
                  - title: MyDisassembler
                    url: https://github.com/Koukyosyumei/MyDisassembler
                    description: Disassembler for X86-64 implemented from scratch in C++.
                  - title: MyCompiler
                    url: https://github.com/Koukyosyumei/MyCompiler
                    description: Toy compiler from a simple language to LLVM-IR implemented from scratch in Haskell.
                  - title: MyPlanner
                    url: https://github.com/Koukyosyumei/MyPlanner
                    description: PDDL Solver implemented from scratch in C++.
                  - title: MyOptimizer
                    url: https://github.com/Koukyosyumei/MyOptimizer
                    description: Implementations of popular optimization and search algorithms.  
          research:
            - title: Fukunaga Lab, The University of Tokyo
              role: "Undergraduate Student"
              date: "Apr. 2023 - Mar. 2023"
              description: "Conducted research on the transit obfuscation problem, which is a new task of privacy-preserving AI planning, under the supervision of Prof. Alex Fukunaga."
            - title: Institute for AI Industry Research, Tsinghua University
              role: Federated Learning & Privacy Computing Intern
              date: "Jan. 2022 ‑ Feb. 2023"
              description: "Conducted research on federated learning and privacy computing under the supervision of Prof. Yang Liu and Prof. Jingjing Liu."  
            - title: Laboratory for Software Design and Analysis, Nara Institute of Science and Technology
              role: Visiting Student
              date: "Aug. 2021 ‑ Sep. 2021" 
              description: "Conducted research on the free‑rider problem of federated learning under the supervision of Prof. Kohei Ichikawa and Prof. Keichi Takahashi."  
          industry:
            - title: Apple Inc.
              role: "Technical Internship: AIML/Software Engineer"
              date: "Feb. 2024 - present"
              description: "Working on AIML/software engineering."
            - title: UTokyo Economic Consulting Inc.
              role: Research Assistant
              date: "Oct. 2020 - present"
              description: "Working on research and social implementations of econometrics and machine learning."  
            - title: RECRUIT
              role: Data Science Intern
              date: "Aug. 2020 - Sep. 2020"
              description: "Worked on a location‑based restaurant recommendation iOS app."
            - title: M3, Inc.
              role: Data Analysis Intern
              date: "Feb. 2020 - Jun. 2020"
              description: "Worked on a data analysis project in the field of medical surveys."  
            - title: FRONTEO, Inc.
              role: Research Intern
              date: "Sep. 2019 ‑ Mar. 2020"
              description: "Worked on the detection of anomaly documents with NLP and network analysis."  

          honor:
            - title: "Funai Overseas Scholarship"
              date: 2024
              url: https://funaifoundation.jp/scholarship/en/scholarship_guidelines_phd.html
              result: Scholarship
              description: "Granted two years of tuition and stipend"
            - title: "Kaggle, Google - Fast or Slow? Predict AI Model Runtime"
              date: 2023
              url: https://www.kaggle.com/competitions/predict-ai-model-runtime
              result: "45th/616 teams (silver medal)" 
              description: "Compiler Optimization, Automated Algorithmic Configuration"  
            - title: "Kaggle, Hungry Geese"
              date: 2021
              url: https://www.kaggle.com/competitions/hungry-geese
              result: "67th/875 teams (bronze medal)"
              description: "AI Agent, Reinforcement Learning"  
            - title: "Kaggle, Santa 2020"
              date: 2021
              url: https://www.kaggle.com/competitions/santa-2020
              result: "52nd/788 teams (bronze medal)"
              description: "AI Agent, Reinforcement Learning, Multi-Armed Bandit"  
            - title: "Kaggle, Google Research Football with Manchester City F.C."
              date: 2020
              url: https://www.kaggle.com/c/google-football
              result: "51st/1138 teams (silver medal)"
              description: "AI Agent, Reinforcement Learning"  
            - title: "Kaggle, Cornell Birdcall Identification"
              date: 2020
              url: https://www.kaggle.com/c/birdsong-recognition
              result: "88th/1390 teams (bronze medal)"
              description: "Audio Classification, Signal Processing"

          service:
            - title: "Reviewer"
              subprojects:
                  - title: "IEEE Transactions on Network Science and Engineering (Impact Factor: 6.7)"
                  - title: "IEEE Transactions on Medical Imaging (Impact Factor: 10.0)"
            - title: "OSS Contributor"
              subprojects:
                  - title: PySyft
                    url: https://github.com/OpenMined/PySyft
                    description: Platform for secure and private Deep Learning
                  - title: Nebula
                    url: https://github.com/vesoft-inc/nebula
                    description: Distributed graph database

    socialIcons:
        - name: Email
          url: mailto:takahashi-hideaki567< a t >g.ecc.u-tokyo.ac.jp
        # - name: CV
        #  url: https://drive.google.com/file/d/17FKt_gU3aWdFuzrKQqYVO8czgktXkUni/view?usp=sharing
            #- name: Location
            #url: location/
            #- name: Office Hours
          #url: officehours/
          #- name: Google Scholar
          #url: https://scholar.google.com/citations?user=cL23w-4AAAAJ
            #- name: YouTube
            #url: https://www.youtube.com/@pmichaillat
            #- name: GitHub
            #url: https://github.com/pmichaillat
            #- name: Substack
            #url: https://pmichaillat.substack.com
            #- name: Twitter
            #url: https://twitter.com/pmichaillat

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Hideaki Takahashi"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
